### ISSUE TITLE
Add typing for all tmt modules

### ISSUE THREAD

**Issue by thrix** [teemtee/tmt#1182]
### Current state of things in general

* `tmt` packages and modules are getting type annotations
* `mypy` is forced to check only a subset of all available files, i.e. files that have been annotated already
  * this limitation will be dropped once all files are annotated
* `mypy` is prevented from following imports, i.e. many of classes imported by plugins are considered to be `Any` by `mypy`
  * this limitation will be dropped once enough files are annotated to limit then number of "untyped foo used in typed context" issues - probably once we're done with "library" modules like `utils.py`, `base.py` and various `__init__.py` under `steps/`
  * removal of this limitation will let `mypy` to cross-compare attributes of child classes with those declared in parent classes, and it will lead to plenty of issues to fix - these are expected, and must be resolved to keep code consistent.

### PRs statuses with dependencies

The following list shows a hierarchy of how PRs depend on each other to show the order in which they should be completed and merged. A higher level means that it should be finished sooner.

Moreover, a review status is provided to know the current state of the PR, maintained by @thrix.

### Needs discussion

N/A

### About

This is the top-level issue tracking implementation of typing for `tmt`. If you will be adding typing for some of the modules, make sure to update this issue.

### Workflow

Mypy is run via pre-commit, to add a module to be checked via `mypy`, update the `mypy.ini` file in the root of the project.

To run `mypy` use (after you updated `mypy.ini`):

```
pre-commit run --all-files mypy
```

### Work items

Please add your name if you start working on it, and link to a pull request once you create it.

- [x] `./bin/tmt` **[mprchlik]** #1573
- [x] `./tmt/base.py` **[mprchlik]** #1457
- [x] `./tmt/beakerlib.py`  **[mvadkert]** #1184 
- [x] `./tmt/cli.py` **[mvadkert]** #1306
- [x] `./tmt/convert.py` **[efedin]** #1259 
- [x] `./tmt/export.py` **[mvadkert]** #1298
- [x] `./tmt/identifier.py`
- [x] `./tmt/__init__.py`
- [x] `./tmt/__main__.py`
- [x] `./tmt/options.py` **[mvadkert]**  #1304
- [x] `./tmt/plugins/__init__.py` **[efedin]** #1238
- [x] `./tmt/steps/__init__.py` **[efedin]** #1221
- [x] `./tmt/steps/discover/__init__.py` **[jhavlin]** #1333
- [x] `./tmt/steps/discover/fmf.py` **[ginger]** https://github.com/teemtee/tmt/pull/1329
- [x] `./tmt/steps/discover/shell.py` **[jhavlin]** #1335
- [x] `./tmt/steps/execute/__init__.py` **[jhavlin]** #1327
- [x] `./tmt/steps/execute/internal.py` **[ginger]** https://github.com/teemtee/tmt/pull/1328
- [x] `./tmt/steps/execute/upgrade.py` **[jhavlin]** https://github.com/teemtee/tmt/pull/1383
- [x] `./tmt/steps/finish/__init__.py` **[ginger]** https://github.com/teemtee/tmt/pull/1302
- [x] `./tmt/steps/finish/ansible.py` **[ginger]** https://github.com/teemtee/tmt/pull/1300
- [x] `./tmt/steps/finish/shell.py` [ginger] https://github.com/teemtee/tmt/pull/1301
- [x] `./tmt/steps/prepare/__init__.py` **[efedin]** #1297 
- [x] `./tmt/steps/prepare/ansible.py` **[ginger]** #1193
- [x] `./tmt/steps/prepare/install.py` **[ginger]** https://github.com/teemtee/tmt/pull/1285
- [x] `./tmt/steps/prepare/multihost.py` **[ginger]** #1203
- [x] `./tmt/steps/prepare/shell.py` **[ginger]** #1224
- [x] `./tmt/steps/provision/__init__.py` **[mprchlik]** #1417
- [x] `./tmt/steps/provision/artemis.py` **[mprchlik]** #1247
- [x] `./tmt/steps/provision/connect.py` **[ginger]** #1286
- [x] `./tmt/steps/provision/local.py` **[jhavlin]** #1419
- [x] `./tmt/steps/provision/podman.py` **[jhavlin]** #1418
- [x] `./tmt/steps/provision/testcloud.py` **[jhavlin]** #1414
- [x] `./tmt/steps/report/__init__.py` **[jhavlin]** #1319
- [x] `./tmt/steps/report/display.py` **[jhavlin]** #1325
- [x] `./tmt/steps/report/html.py` **[jhavlin]** #1324
- [x] `./tmt/steps/report/junit.py` **[jhavlin]** #1323 
- [x] `./tmt/templates.py`
- [x] `./tmt/utils.py`
- [x] update linters #1555
- [x] enable `follow_imports = normal` #1598

After enabling `follow_imports`, the following would take place:

- [x] revisit all uses of `cast()` #1566
  - #1600
- [x] revisit all uses of `# type: ignore` #1567
  - #1617
- [x] revisit all uses of `Any` #1568
  - #1603
- [x] run full test suite

**Comment by ukulekek** [comment]
I will work on ` ./tmt/plugins/__init__.py`. Can't edit the description

**Comment by happz** [comment]
@ukulekek OP updated, thank you.

**Comment by thrix** [comment]
@ukulekek maybe we can ask politely @psss to add you to colabs, or what perms it needs :)

**Comment by psss** [comment]
Permissions should be set up, @ukulekek, please check.

**Comment by guy9050** [comment]
@psss can you please give me permissions too or add my name for `./tmt/steps/prepare/ansible.py` ?

**Comment by psss** [comment]
Sure, permissions should be set up. @guy9050, please have a look.

**Comment by guy9050** [comment]
@psss seems like I still can't edit it..

**Comment by guy9050** [comment]
@psss I've just accepted it now, thank you!

**Comment by guy9050** [comment]
@psss I've joined the org, logged out and in again but still no option to edit this issue. Can you please check? thanks

**Comment by psss** [comment]
@guy9050, it seems you have still a pending [invitation](https://github.com/teemtee/tmt/invitations) to the `tmt` project.

**Comment by guy9050** [comment]
I've added a "Needs discussion" section. I would like to initiate a discussion about it and hear your thoughts. @thrix @janhavlin @psss @happz

**Comment by happz** [comment]
@thrix (I moved sections you added before the work items, to keep them on top of the ticket - I find it more readable than scrolling under the work items list.)

**Comment by psss** [comment]
Full test suite executed, ran into a couple of issues:

* `/tests/provision/virtual/dependencies` ... fails most probably because of the nested virtualization
* `/tests/run/shell` ... permission denied problem
* `/tests/provision/reboot` ... looks like a virtual provision error
* `/tests/discover/libraries` ... seems to reveal a regression in `recommend` with `beakerlib` libraries
* `/tests/execute/upgrade/full` ... a traceback during `GuestTestcloud._image.prepare()`

Regarding libraries: It seems they should be supported for both `require` and `recommend` and work for both in the same way.

**Comment by happz** [comment]
> Full test suite executed, ran into a couple of issues:
> 
> * `/tests/provision/virtual/dependencies` ... fails most probably because of the nested virtualization
> * `/tests/run/shell` ... permission denied problem
> * `/tests/provision/reboot` ... looks like a virtual provision error
> * `/tests/discover/libraries` ... seems to reveal a regression in `recommend` with `beakerlib` libraries
> * `/tests/execute/upgrade/full` ... a traceback during `GuestTestcloud._image.prepare()`
> 
> Regarding libraries: It seems they should be supported for both `require` and `recommend` and work for both in the same way.

A fix for `/tests/discover/libraries` should be #1630.

**Comment by lukaszachy** [comment]
`/tests/execute/upgrade/full` is likely a  "cannot download image" problem - #1265

**Comment by lukaszachy** [comment]
`/tests/provision/virtual/dependencies` Needs  more than 60s seconds to boot & ssh connect when in nested few levels down. (on my VM in VM it was 80s)

**Comment by lukaszachy** [comment]
/tests/run/shell -> #1632

**Comment by psss** [comment]
Full test suite successfully passed in TJ#7170019 against commit d737ec6a257c714bfd447b3a3d4470575ab92952.

**Comment by psss** [comment]
All typing annotation tasks have been completed! \o/
Thanks to all for great collaboration on this huge task!
