### ISSUE TITLE
Convert export functionality into plugins for various formats for easier extensibility

### ISSUE THREAD

**Issue by happz** [teemtee/tmt#1679]
Export code is interwoven through base and export modules. It would be much nicer to define a clear API for export plugins and isolate each target format (YAML, reST, but also nitrate or polarion) into its own plugin. Adding new formats would become much simpler, with less boilerplate involved.

(I want an export to Asciidoc, and I don't like how reST is implemented :)

* [x] convert export code to plugin-based approach (not perfect, but good enough to build upon): #1709 
* [x] convert ReST export to use templates: #1738 
* [x] add a generic template-consuming export plugin: #1767 
* [x] require jinja2 by default, not when a `report-html` is installed: #1768
